import type { Converter, ConverterCategory } from '@/types'
import {
  jsonToTypescript, jsonToJavascript, jsonToYaml, jsonToXml,
  jsonToCsv, jsonToSql, jsonBeautify, jsonMinify, csvToJson,
} from '@/converters/json.converter'
import { yamlToJson, yamlToXml, yamlToTypescript } from '@/converters/yaml.converter'
import { xmlToJson, xmlToYaml, xmlBeautify } from '@/converters/xml.converter'
import { typescriptToJavascript, javascriptToTypescript, jsBeautify, jsonToJsObject } from '@/converters/code.converter'
import { markdownToHtml, htmlToMarkdown, htmlBeautify, htmlMinify } from '@/converters/markup.converter'
import {
  base64Encode, base64Decode, urlEncode, urlDecode, jwtDecode,
  htmlEntitiesEncode, htmlEntitiesDecode,
  decimalToBinary, binaryToDecimal, decimalToHex, hexToDecimal,
  timestampToDate, dateToTimestamp,
} from '@/converters/encoding.converter'
import { hexToAll, rgbToAll, hslToAll } from '@/converters/color.converter'
import { cssToScss, cssMinify, cssBeautify, cssToTailwind } from '@/converters/css.converter'

// Helper: wrap async converter — preserves options param
function wrap(fn: (input: string, options?: Record<string, string>) => Promise<import('@/types').ConvertResult>) {
  return (input: string, options?: Record<string, string>) => fn(input, options)
}

// ─── Converter Definitions ─────────────────────────────────────────────────

const CONVERTERS: Converter[] = [
  // ── JSON Category ──────────────────────────────────────────────────────
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    shortName: 'JSON → TS',
    description: 'Convert JSON objects to TypeScript interfaces with proper types',
    longDescription: 'Paste your JSON data and instantly generate TypeScript interfaces. Supports nested objects, arrays, optional fields, and union types. Perfect for developers working with REST APIs.',
    category: 'json',
    inputLanguage: 'json',
    outputLanguage: 'typescript',
    inputPlaceholder: '{\n  "userId": 1,\n  "name": "Alice",\n  "email": "alice@example.com",\n  "roles": ["admin", "user"],\n  "address": {\n    "city": "Bangkok",\n    "country": "TH"\n  }\n}',
    convert: jsonToTypescript,
    seoTitle: 'JSON to TypeScript Interface Generator – Free Online Tool',
    seoDescription: 'Convert JSON to TypeScript interfaces instantly. Auto-generates nested interfaces, arrays, optional fields, and union types from your JSON data.',
    seoKeywords: ['json to typescript', 'json to ts', 'json typescript interface', 'generate typescript from json', 'json to interface'],
    urlAliases: ['json-to-ts', 'json2typescript', 'json2ts'],
    relatedConverters: ['json-to-javascript', 'json-beautify', 'yaml-to-typescript', 'typescript-to-javascript'],
    isPopular: true,
  },
  {
    id: 'json-to-javascript',
    name: 'JSON to JavaScript',
    shortName: 'JSON → JS',
    description: 'Convert JSON to a JavaScript const variable declaration',
    longDescription: 'Convert your JSON data into a JavaScript const declaration. Useful for embedding data directly in JavaScript/Node.js files.',
    category: 'json',
    inputLanguage: 'json',
    outputLanguage: 'javascript',
    inputPlaceholder: '{\n  "name": "DevConvert",\n  "version": "1.0.0",\n  "features": ["fast", "free", "no-signup"]\n}',
    convert: jsonToJavascript,
    seoTitle: 'JSON to JavaScript Object Converter – Free Online Tool',
    seoDescription: 'Convert JSON to JavaScript const declaration online. Fast, free, and instant conversion in your browser.',
    seoKeywords: ['json to javascript', 'json to js', 'json to js object', 'convert json javascript'],
    urlAliases: ['json-to-js', 'json2javascript', 'json2js'],
    relatedConverters: ['json-to-typescript', 'json-to-yaml', 'javascript-to-typescript'],
    isPopular: true,
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    shortName: 'JSON → YAML',
    description: 'Convert JSON to YAML format for config files and Kubernetes manifests',
    longDescription: 'Convert JSON data to YAML format. YAML is widely used in configuration files, CI/CD pipelines, Docker Compose, and Kubernetes manifests. Preserves all data types.',
    category: 'json',
    inputLanguage: 'json',
    outputLanguage: 'yaml',
    inputPlaceholder: '{\n  "apiVersion": "apps/v1",\n  "kind": "Deployment",\n  "metadata": {\n    "name": "my-app",\n    "replicas": 3\n  }\n}',
    convert: wrap(jsonToYaml),
    seoTitle: 'JSON to YAML Converter – Free Online Tool',
    seoDescription: 'Convert JSON to YAML online instantly. Perfect for Docker, Kubernetes, and GitHub Actions config files. Free, no signup required.',
    seoKeywords: ['json to yaml', 'json yaml converter', 'convert json to yaml', 'json2yaml'],
    urlAliases: ['json2yaml'],
    relatedConverters: ['yaml-to-json', 'json-beautify', 'json-to-xml'],
    isPopular: true,
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML',
    shortName: 'JSON → XML',
    description: 'Convert JSON data to XML format',
    longDescription: 'Transform JSON data into well-formatted XML. Supports nested objects, arrays, and all JSON data types. Useful for SOAP APIs and legacy system integrations.',
    category: 'json',
    inputLanguage: 'json',
    outputLanguage: 'xml',
    inputPlaceholder: '{\n  "user": {\n    "id": 1,\n    "name": "Alice",\n    "tags": ["admin", "user"]\n  }\n}',
    convert: jsonToXml,
    seoTitle: 'JSON to XML Converter – Free Online Tool',
    seoDescription: 'Convert JSON to XML format online. Free, instant, no installation needed.',
    seoKeywords: ['json to xml', 'json xml converter', 'convert json xml'],
    urlAliases: ['json2xml'],
    relatedConverters: ['xml-to-json', 'json-to-yaml'],
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    shortName: 'JSON → CSV',
    description: 'Convert JSON arrays to CSV for Excel and spreadsheets',
    longDescription: 'Convert JSON arrays to CSV format. Automatically extracts headers from object keys and handles nested values. Perfect for data export to Excel, Google Sheets, or database imports.',
    category: 'json',
    inputLanguage: 'json',
    outputLanguage: 'plaintext',
    inputPlaceholder: '[\n  { "id": 1, "name": "Alice", "email": "alice@example.com" },\n  { "id": 2, "name": "Bob", "email": "bob@example.com" }\n]',
    convert: jsonToCsv,
    seoTitle: 'JSON to CSV Converter – Free Online Tool',
    seoDescription: 'Convert JSON arrays to CSV format online. Export to Excel, Google Sheets instantly. Free, no signup.',
    seoKeywords: ['json to csv', 'json csv converter', 'export json to csv', 'json to excel'],
    urlAliases: ['json2csv'],
    relatedConverters: ['csv-to-json', 'json-to-sql'],
    isPopular: true,
  },
  {
    id: 'json-to-sql',
    name: 'JSON to SQL',
    shortName: 'JSON → SQL',
    description: 'Generate SQL CREATE TABLE and INSERT statements from JSON',
    longDescription: 'Convert JSON arrays to SQL INSERT statements with an auto-generated CREATE TABLE. Infers column types from data. Supports NULL handling.',
    category: 'json',
    inputLanguage: 'json',
    outputLanguage: 'sql',
    inputPlaceholder: '[\n  { "id": 1, "username": "alice", "score": 9.5, "active": true },\n  { "id": 2, "username": "bob", "score": 7.2, "active": false }\n]',
    convert: jsonToSql,
    seoTitle: 'JSON to SQL INSERT Generator – Free Online Tool',
    seoDescription: 'Generate SQL INSERT and CREATE TABLE statements from JSON data. Free online tool for developers.',
    seoKeywords: ['json to sql', 'json to sql insert', 'json sql generator', 'json to mysql'],
    urlAliases: ['json2sql'],
    relatedConverters: ['csv-to-json', 'json-to-csv'],
  },
  {
    id: 'json-beautify',
    name: 'JSON Beautify',
    shortName: 'JSON Beautify',
    description: 'Format and pretty-print minified JSON',
    longDescription: 'Beautify and format minified or compact JSON data. Adds proper indentation, line breaks, and makes JSON human-readable. Also validates your JSON syntax.',
    category: 'json',
    inputLanguage: 'json',
    outputLanguage: 'json',
    inputPlaceholder: '{"name":"DevConvert","version":"1.0","features":["fast","free"]}',
    convert: jsonBeautify,
    seoTitle: 'JSON Beautifier & Formatter – Free Online Tool',
    seoDescription: 'Beautify and format JSON online. Pretty-print minified JSON with proper indentation. Free JSON formatter and validator.',
    seoKeywords: ['json beautify', 'json formatter', 'json pretty print', 'format json online', 'json validator'],
    urlAliases: ['json-formatter', 'json-pretty-print', 'json-format'],
    relatedConverters: ['json-minify', 'json-to-typescript'],
    isPopular: true,
  },
  {
    id: 'json-minify',
    name: 'JSON Minify',
    shortName: 'JSON Minify',
    description: 'Minify JSON by removing whitespace',
    longDescription: 'Compress and minify JSON by removing all unnecessary whitespace and line breaks. Reduces file size for API responses and storage.',
    category: 'json',
    inputLanguage: 'json',
    outputLanguage: 'json',
    inputPlaceholder: '{\n  "name": "DevConvert",\n  "version": "1.0",\n  "features": [\n    "fast",\n    "free"\n  ]\n}',
    convert: jsonMinify,
    seoTitle: 'JSON Minifier – Compress JSON Online | Free Tool',
    seoDescription: 'Minify and compress JSON online. Remove whitespace to reduce JSON file size. Free, instant tool.',
    seoKeywords: ['json minify', 'json minifier', 'compress json', 'json compress', 'minify json online'],
    urlAliases: ['json-compress', 'json-minifier'],
    relatedConverters: ['json-beautify'],
  },
  {
    id: 'json-to-js-object',
    name: 'JSON to JS Object',
    shortName: 'JSON → JS Object',
    description: 'Convert JSON to JavaScript object literal (unquoted keys)',
    longDescription: 'Convert JSON to a JavaScript object literal with unquoted keys where possible. Useful for embedding data in JS files with cleaner syntax.',
    category: 'json',
    inputLanguage: 'json',
    outputLanguage: 'javascript',
    inputPlaceholder: '{\n  "apiUrl": "https://api.example.com",\n  "timeout": 5000,\n  "enabled": true\n}',
    convert: jsonToJsObject,
    seoTitle: 'JSON to JavaScript Object Literal Converter',
    seoDescription: 'Convert JSON to JavaScript object with unquoted keys. Free online developer tool.',
    seoKeywords: ['json to js object', 'json to javascript object', 'json object literal'],
    relatedConverters: ['json-to-javascript', 'json-to-typescript'],
  },

  // ── YAML Category ──────────────────────────────────────────────────────
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    shortName: 'YAML → JSON',
    description: 'Convert YAML config files to JSON format',
    longDescription: 'Convert YAML files to JSON. Supports all YAML features including anchors, multi-line strings, and complex data types. Perfect for parsing Docker Compose, Kubernetes, and GitHub Actions files.',
    category: 'json',
    inputLanguage: 'yaml',
    outputLanguage: 'json',
    inputPlaceholder: 'name: DevConvert\nversion: "1.0"\nfeatures:\n  - fast\n  - free\n  - no-signup\nconfig:\n  port: 3000\n  debug: false',
    convert: wrap(yamlToJson),
    seoTitle: 'YAML to JSON Converter – Free Online Tool',
    seoDescription: 'Convert YAML to JSON online instantly. Supports Docker Compose, Kubernetes, and GitHub Actions YAML files. Free, no signup.',
    seoKeywords: ['yaml to json', 'yaml json converter', 'convert yaml to json', 'yaml2json'],
    urlAliases: ['yaml2json'],
    relatedConverters: ['json-to-yaml', 'yaml-to-xml', 'json-beautify'],
    isPopular: true,
  },
  {
    id: 'yaml-to-xml',
    name: 'YAML to XML',
    shortName: 'YAML → XML',
    description: 'Convert YAML to XML format',
    longDescription: 'Transform YAML data into XML format. Useful for converting configuration files for systems that require XML input.',
    category: 'json',
    inputLanguage: 'yaml',
    outputLanguage: 'xml',
    inputPlaceholder: 'server:\n  host: localhost\n  port: 8080\n  ssl: true\n  endpoints:\n    - /api/v1\n    - /health',
    convert: wrap(yamlToXml),
    seoTitle: 'YAML to XML Converter – Free Online Tool',
    seoDescription: 'Convert YAML to XML online. Free developer tool for data format conversion.',
    seoKeywords: ['yaml to xml', 'yaml xml converter', 'convert yaml xml'],
    relatedConverters: ['yaml-to-json', 'xml-to-json'],
  },
  {
    id: 'yaml-to-typescript',
    name: 'YAML to TypeScript',
    shortName: 'YAML → TS',
    description: 'Generate TypeScript interfaces from YAML data',
    longDescription: 'Convert YAML files to TypeScript interface definitions. Useful for generating types from configuration schemas.',
    category: 'json',
    inputLanguage: 'yaml',
    outputLanguage: 'typescript',
    inputPlaceholder: 'user:\n  id: 1\n  name: Alice\n  email: alice@example.com\n  roles:\n    - admin\n    - user',
    convert: wrap(yamlToTypescript),
    seoTitle: 'YAML to TypeScript Interface Generator – Free Tool',
    seoDescription: 'Generate TypeScript interfaces from YAML data. Free online tool for developers.',
    seoKeywords: ['yaml to typescript', 'yaml typescript interface', 'yaml to ts'],
    relatedConverters: ['json-to-typescript', 'yaml-to-json'],
  },

  // ── XML Category ────────────────────────────────────────────────────────
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    shortName: 'XML → JSON',
    description: 'Convert XML to JSON format',
    longDescription: 'Transform XML documents into JSON format. Preserves attributes, nested elements, and text content. Perfect for modernizing SOAP-based APIs or legacy XML data.',
    category: 'json',
    inputLanguage: 'xml',
    outputLanguage: 'json',
    inputPlaceholder: '<?xml version="1.0"?>\n<user id="1">\n  <name>Alice</name>\n  <email>alice@example.com</email>\n  <roles>\n    <role>admin</role>\n    <role>user</role>\n  </roles>\n</user>',
    convert: wrap(xmlToJson),
    seoTitle: 'XML to JSON Converter – Free Online Tool',
    seoDescription: 'Convert XML to JSON online instantly. Supports attributes, nested elements, and arrays. Free developer tool.',
    seoKeywords: ['xml to json', 'xml json converter', 'convert xml to json', 'xml2json'],
    urlAliases: ['xml2json'],
    relatedConverters: ['json-to-xml', 'xml-to-yaml', 'json-beautify'],
    isPopular: true,
  },
  {
    id: 'xml-to-yaml',
    name: 'XML to YAML',
    shortName: 'XML → YAML',
    description: 'Convert XML to YAML format',
    longDescription: 'Transform XML documents into YAML format. Clean, readable output for configuration files and data exchange.',
    category: 'json',
    inputLanguage: 'xml',
    outputLanguage: 'yaml',
    inputPlaceholder: '<?xml version="1.0"?>\n<config>\n  <host>localhost</host>\n  <port>8080</port>\n  <debug>true</debug>\n</config>',
    convert: wrap(xmlToYaml),
    seoTitle: 'XML to YAML Converter – Free Online Tool',
    seoDescription: 'Convert XML to YAML online. Free developer tool for format conversion.',
    seoKeywords: ['xml to yaml', 'xml yaml converter', 'xml2yaml'],
    relatedConverters: ['yaml-to-json', 'xml-to-json'],
  },
  {
    id: 'xml-beautify',
    name: 'XML Beautify',
    shortName: 'XML Beautify',
    description: 'Format and indent XML documents',
    longDescription: 'Beautify and format XML documents with proper indentation. Makes minified or compressed XML human-readable.',
    category: 'json',
    inputLanguage: 'xml',
    outputLanguage: 'xml',
    inputPlaceholder: '<?xml version="1.0"?><root><user id="1"><name>Alice</name><email>alice@example.com</email></user></root>',
    convert: xmlBeautify,
    seoTitle: 'XML Formatter & Beautifier – Free Online Tool',
    seoDescription: 'Beautify and format XML online. Add proper indentation to minified XML. Free XML formatter.',
    seoKeywords: ['xml formatter', 'xml beautify', 'xml pretty print', 'format xml online'],
    relatedConverters: ['xml-to-json', 'xml-to-yaml'],
  },

  // ── CSV Category ────────────────────────────────────────────────────────
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    shortName: 'CSV → JSON',
    description: 'Convert CSV files to JSON arrays',
    longDescription: 'Convert CSV data to JSON arrays. Automatically parses headers, handles quoted fields, and infers data types (numbers, booleans, null). Perfect for data processing workflows.',
    category: 'data',
    inputLanguage: 'plaintext',
    outputLanguage: 'json',
    inputPlaceholder: 'id,name,email,score,active\n1,Alice,alice@example.com,9.5,true\n2,Bob,bob@example.com,7.2,false\n3,Charlie,charlie@example.com,8.1,true',
    convert: csvToJson,
    seoTitle: 'CSV to JSON Converter – Free Online Tool',
    seoDescription: 'Convert CSV files to JSON arrays online. Auto-detects headers and data types. Free, instant, no signup.',
    seoKeywords: ['csv to json', 'csv json converter', 'convert csv to json', 'csv2json', 'excel to json'],
    urlAliases: ['csv2json'],
    relatedConverters: ['json-to-csv', 'json-beautify'],
    isPopular: true,
  },

  // ── Code Category ───────────────────────────────────────────────────────
  {
    id: 'typescript-to-javascript',
    name: 'TypeScript to JavaScript',
    shortName: 'TS → JS',
    description: 'Strip TypeScript types and convert to plain JavaScript',
    longDescription: 'Remove TypeScript type annotations, interfaces, generics, and access modifiers to produce clean JavaScript. Useful for sharing code with non-TypeScript projects.',
    category: 'code',
    inputLanguage: 'typescript',
    outputLanguage: 'javascript',
    inputPlaceholder: 'interface User {\n  id: number;\n  name: string;\n  email: string;\n}\n\nconst getUser = async (id: number): Promise<User> => {\n  const response = await fetch(`/api/users/${id}`);\n  return response.json() as User;\n};',
    convert: typescriptToJavascript,
    seoTitle: 'TypeScript to JavaScript Converter – Free Online Tool',
    seoDescription: 'Convert TypeScript to JavaScript by removing type annotations. Strip TS types online, free and instant.',
    seoKeywords: ['typescript to javascript', 'ts to js', 'remove typescript types', 'typescript converter', 'ts2js'],
    urlAliases: ['ts-to-js', 'typescript-to-js', 'ts2js'],
    relatedConverters: ['javascript-to-typescript', 'json-to-typescript'],
    isPopular: true,
  },
  {
    id: 'javascript-to-typescript',
    name: 'JavaScript to TypeScript',
    shortName: 'JS → TS',
    description: 'Convert JavaScript to TypeScript with basic type annotations',
    longDescription: 'Add TypeScript hints to JavaScript code. Converts require() to import statements and adds basic type annotations. For best results, add manual type refinements afterward.',
    category: 'code',
    inputLanguage: 'javascript',
    outputLanguage: 'typescript',
    inputPlaceholder: "const axios = require('axios');\n\nconst fetchUser = async (id) => {\n  const response = await axios.get(`/api/users/${id}`);\n  return response.data;\n};\n\nexport { fetchUser };",
    convert: javascriptToTypescript,
    seoTitle: 'JavaScript to TypeScript Converter – Free Online Tool',
    seoDescription: 'Convert JavaScript to TypeScript online. Add type annotations and convert require to import. Free developer tool.',
    seoKeywords: ['javascript to typescript', 'js to ts', 'convert js to typescript', 'js2ts'],
    urlAliases: ['js-to-ts', 'js2ts'],
    relatedConverters: ['typescript-to-javascript', 'json-to-typescript'],
    isPopular: true,
  },

  // ── Markup Category ─────────────────────────────────────────────────────
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    shortName: 'MD → HTML',
    description: 'Convert Markdown to HTML with a complete page template',
    longDescription: 'Convert Markdown documents to HTML. Supports GitHub Flavored Markdown (GFM) including tables, task lists, strikethrough, and fenced code blocks. Generates a complete HTML page with basic styling.',
    category: 'markup',
    inputLanguage: 'markdown',
    outputLanguage: 'html',
    inputPlaceholder: '# Hello World\n\n## Features\n\n- **Fast** conversion\n- *Free* to use\n- No signup required\n\n## Code Example\n\n```javascript\nconst greeting = "Hello, World!";\nconsole.log(greeting);\n```\n\n> This is a blockquote\n\n| Name | Value |\n|------|-------|\n| Dev  | Convert |',
    convert: wrap(markdownToHtml),
    seoTitle: 'Markdown to HTML Converter – Free Online Tool',
    seoDescription: 'Convert Markdown to HTML online. Supports GitHub Flavored Markdown, tables, code blocks, and more. Free, instant.',
    seoKeywords: ['markdown to html', 'md to html', 'markdown html converter', 'markdown converter', 'markdown2html'],
    urlAliases: ['md-to-html', 'markdown2html'],
    relatedConverters: ['html-to-markdown', 'html-beautify'],
    isPopular: true,
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    shortName: 'HTML → MD',
    description: 'Convert HTML to clean Markdown format',
    longDescription: 'Transform HTML documents into Markdown format. Converts headings, paragraphs, lists, links, images, and code blocks. Great for migrating content to documentation platforms.',
    category: 'markup',
    inputLanguage: 'html',
    outputLanguage: 'markdown',
    inputPlaceholder: '<h1>Hello World</h1>\n<p>This is a <strong>sample</strong> HTML page with <em>formatting</em>.</p>\n<ul>\n  <li>Item one</li>\n  <li>Item two</li>\n</ul>\n<a href="https://example.com">Visit Example</a>',
    convert: wrap(htmlToMarkdown),
    seoTitle: 'HTML to Markdown Converter – Free Online Tool',
    seoDescription: 'Convert HTML to Markdown online. Transform web pages to Markdown for documentation, README files, and more. Free.',
    seoKeywords: ['html to markdown', 'html markdown converter', 'html2markdown', 'convert html to md'],
    urlAliases: ['html-to-md', 'html2markdown'],
    relatedConverters: ['markdown-to-html', 'html-beautify'],
  },
  {
    id: 'html-beautify',
    name: 'HTML Beautify',
    shortName: 'HTML Beautify',
    description: 'Format and indent HTML documents',
    longDescription: 'Beautify and format HTML code with proper indentation. Makes minified HTML human-readable and easier to maintain.',
    category: 'markup',
    inputLanguage: 'html',
    outputLanguage: 'html',
    inputPlaceholder: '<!DOCTYPE html><html><head><title>Test</title></head><body><div class="container"><h1>Hello</h1><p>World</p></div></body></html>',
    convert: htmlBeautify,
    seoTitle: 'HTML Formatter & Beautifier – Free Online Tool',
    seoDescription: 'Beautify and format HTML code online. Add proper indentation to minified HTML. Free HTML formatter.',
    seoKeywords: ['html formatter', 'html beautify', 'html pretty print', 'format html', 'html indentation'],
    urlAliases: ['html-formatter', 'html-format'],
    relatedConverters: ['html-minify', 'html-to-markdown'],
  },
  {
    id: 'html-minify',
    name: 'HTML Minify',
    shortName: 'HTML Minify',
    description: 'Minify HTML by removing whitespace and comments',
    longDescription: 'Compress HTML by removing unnecessary whitespace, line breaks, and comments. Reduces page load time and file size.',
    category: 'markup',
    inputLanguage: 'html',
    outputLanguage: 'html',
    inputPlaceholder: '<!DOCTYPE html>\n<html>\n  <head>\n    <!-- Comment -->\n    <title>Test</title>\n  </head>\n  <body>\n    <div class="container">\n      <h1>Hello</h1>\n    </div>\n  </body>\n</html>',
    convert: htmlMinify,
    seoTitle: 'HTML Minifier – Compress HTML Online | Free Tool',
    seoDescription: 'Minify HTML online. Remove whitespace and comments to reduce file size. Free HTML minifier.',
    seoKeywords: ['html minify', 'html minifier', 'compress html', 'html compressor'],
    urlAliases: ['html-compress', 'html-minifier'],
    relatedConverters: ['html-beautify'],
  },

  // ── Encoding Category ───────────────────────────────────────────────────
  {
    id: 'base64-encode',
    name: 'Base64 Encode',
    shortName: 'Text → Base64',
    description: 'Encode text to Base64 format',
    longDescription: 'Encode any text to Base64 format. Used in HTTP Basic Authentication, email attachments, and data URLs. Supports Unicode and special characters.',
    category: 'encoding',
    inputLanguage: 'plaintext',
    outputLanguage: 'plaintext',
    inputPlaceholder: 'Hello, World!\n\nThis text will be encoded to Base64.',
    convert: base64Encode,
    seoTitle: 'Base64 Encoder – Encode Text to Base64 Online',
    seoDescription: 'Encode text to Base64 online instantly. Free Base64 encoder with Unicode support. No installation needed.',
    seoKeywords: ['base64 encode', 'base64 encoder', 'encode base64', 'text to base64', 'base64 online'],
    urlAliases: ['text-to-base64', 'encode-base64'],
    relatedConverters: ['base64-decode', 'url-encode'],
    isPopular: true,
  },
  {
    id: 'base64-decode',
    name: 'Base64 Decode',
    shortName: 'Base64 → Text',
    description: 'Decode Base64 encoded strings back to text',
    longDescription: 'Decode Base64 encoded strings to their original text. Supports standard and URL-safe Base64 encoding.',
    category: 'encoding',
    inputLanguage: 'plaintext',
    outputLanguage: 'plaintext',
    inputPlaceholder: 'SGVsbG8sIFdvcmxkIQ==',
    convert: base64Decode,
    seoTitle: 'Base64 Decoder – Decode Base64 to Text Online',
    seoDescription: 'Decode Base64 to text online instantly. Free Base64 decoder. No installation needed.',
    seoKeywords: ['base64 decode', 'base64 decoder', 'decode base64', 'base64 to text'],
    urlAliases: ['base64-to-text', 'decode-base64'],
    relatedConverters: ['base64-encode', 'url-decode'],
    isPopular: true,
  },
  {
    id: 'url-encode',
    name: 'URL Encode',
    shortName: 'URL Encode',
    description: 'Encode special characters in URLs',
    longDescription: 'Percent-encode special characters in URLs. Essential for passing query parameters and handling non-ASCII characters in URLs safely.',
    category: 'encoding',
    inputLanguage: 'plaintext',
    outputLanguage: 'plaintext',
    inputPlaceholder: 'https://example.com/search?q=hello world&lang=th&tag=c# programming',
    convert: urlEncode,
    seoTitle: 'URL Encoder – Percent Encode URLs Online',
    seoDescription: 'URL encode special characters online. Percent-encode URLs for safe transmission. Free online tool.',
    seoKeywords: ['url encode', 'url encoder', 'percent encode', 'encode url', 'url encoding'],
    relatedConverters: ['url-decode', 'base64-encode'],
  },
  {
    id: 'url-decode',
    name: 'URL Decode',
    shortName: 'URL Decode',
    description: 'Decode percent-encoded URLs',
    longDescription: 'Decode percent-encoded URLs back to their original, human-readable form. Useful for debugging API calls and reading encoded URLs.',
    category: 'encoding',
    inputLanguage: 'plaintext',
    outputLanguage: 'plaintext',
    inputPlaceholder: 'https%3A%2F%2Fexample.com%2Fsearch%3Fq%3Dhello%20world%26lang%3Dth',
    convert: urlDecode,
    seoTitle: 'URL Decoder – Decode Percent Encoded URLs Online',
    seoDescription: 'Decode URL encoded strings online. Convert %20 and other percent-encoded characters. Free tool.',
    seoKeywords: ['url decode', 'url decoder', 'percent decode', 'decode url'],
    relatedConverters: ['url-encode', 'base64-decode'],
  },
  {
    id: 'jwt-decode',
    name: 'JWT Decoder',
    shortName: 'JWT Decode',
    description: 'Decode and inspect JWT tokens (header, payload, expiry)',
    longDescription: 'Decode JWT (JSON Web Token) and display header, payload, and metadata. Shows issuer, expiry date, and whether the token has expired. Note: does not verify signature.',
    category: 'encoding',
    inputLanguage: 'plaintext',
    outputLanguage: 'json',
    inputPlaceholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
    convert: jwtDecode,
    seoTitle: 'JWT Decoder – Decode JSON Web Tokens Online',
    seoDescription: 'Decode and inspect JWT tokens online. View header, payload, and expiry. Free online JWT debugger.',
    seoKeywords: ['jwt decode', 'jwt decoder', 'decode jwt', 'jwt token inspector', 'json web token decode'],
    urlAliases: ['jwt-debugger', 'decode-jwt'],
    relatedConverters: ['base64-decode', 'json-beautify'],
    isPopular: true,
  },
  {
    id: 'html-entities-encode',
    name: 'HTML Entities Encode',
    shortName: 'HTML Encode',
    description: 'Encode special characters to HTML entities',
    longDescription: 'Convert special characters like <, >, &, " to their HTML entity equivalents (&lt;, &gt;, &amp;, &quot;). Essential for safely displaying user input in HTML.',
    category: 'encoding',
    inputLanguage: 'plaintext',
    outputLanguage: 'html',
    inputPlaceholder: '<script>alert("XSS Attack!");</script>\n<b>Hello & "World"</b>',
    convert: htmlEntitiesEncode,
    seoTitle: 'HTML Entities Encoder – Escape HTML Online',
    seoDescription: 'Encode HTML special characters to entities online. Escape <, >, &, " for safe HTML display. Free tool.',
    seoKeywords: ['html encode', 'html entities encode', 'html escape', 'escape html', 'html encoding'],
    relatedConverters: ['html-entities-decode', 'html-beautify'],
  },
  {
    id: 'html-entities-decode',
    name: 'HTML Entities Decode',
    shortName: 'HTML Decode',
    description: 'Decode HTML entities back to plain characters',
    longDescription: 'Convert HTML entities (&lt;, &gt;, &amp;, &quot;) back to their original characters. Useful for reading HTML-encoded content.',
    category: 'encoding',
    inputLanguage: 'html',
    outputLanguage: 'plaintext',
    inputPlaceholder: '&lt;script&gt;alert(&quot;Hello World&quot;);&lt;/script&gt;\n&amp;amp; is a double-encoded ampersand',
    convert: htmlEntitiesDecode,
    seoTitle: 'HTML Entities Decoder – Unescape HTML Online',
    seoDescription: 'Decode HTML entities online. Convert &lt; &gt; &amp; back to characters. Free HTML decoder.',
    seoKeywords: ['html decode', 'html entities decode', 'html unescape', 'unescape html'],
    relatedConverters: ['html-entities-encode'],
  },
  {
    id: 'decimal-to-binary',
    name: 'Decimal to Binary',
    shortName: 'Dec → Bin',
    description: 'Convert decimal numbers to binary representation',
    longDescription: 'Convert decimal (base-10) numbers to binary (base-2). Also shows octal and hexadecimal representations.',
    category: 'utility',
    inputLanguage: 'plaintext',
    outputLanguage: 'plaintext',
    inputPlaceholder: '255',
    convert: decimalToBinary,
    seoTitle: 'Decimal to Binary Converter – Free Online Tool',
    seoDescription: 'Convert decimal to binary online. Also shows octal and hex. Free number base converter.',
    seoKeywords: ['decimal to binary', 'dec to bin', 'number base converter', 'binary converter'],
    relatedConverters: ['binary-to-decimal', 'decimal-to-hex'],
  },
  {
    id: 'binary-to-decimal',
    name: 'Binary to Decimal',
    shortName: 'Bin → Dec',
    description: 'Convert binary numbers to decimal',
    longDescription: 'Convert binary (base-2) numbers to decimal (base-10). Also shows octal and hexadecimal representations.',
    category: 'utility',
    inputLanguage: 'plaintext',
    outputLanguage: 'plaintext',
    inputPlaceholder: '11111111',
    convert: binaryToDecimal,
    seoTitle: 'Binary to Decimal Converter – Free Online Tool',
    seoDescription: 'Convert binary to decimal online. Free number base converter with binary, octal, decimal, and hex.',
    seoKeywords: ['binary to decimal', 'bin to dec', 'binary converter', 'number converter'],
    relatedConverters: ['decimal-to-binary', 'hex-to-decimal'],
  },
  {
    id: 'decimal-to-hex',
    name: 'Decimal to Hex',
    shortName: 'Dec → Hex',
    description: 'Convert decimal numbers to hexadecimal',
    longDescription: 'Convert decimal (base-10) numbers to hexadecimal (base-16). Commonly used in web colors, memory addresses, and low-level programming.',
    category: 'utility',
    inputLanguage: 'plaintext',
    outputLanguage: 'plaintext',
    inputPlaceholder: '255',
    convert: decimalToHex,
    seoTitle: 'Decimal to Hex Converter – Free Online Tool',
    seoDescription: 'Convert decimal to hexadecimal online. Free number base converter.',
    seoKeywords: ['decimal to hex', 'dec to hex', 'decimal hexadecimal converter'],
    relatedConverters: ['hex-to-decimal', 'decimal-to-binary'],
  },
  {
    id: 'hex-to-decimal',
    name: 'Hex to Decimal',
    shortName: 'Hex → Dec',
    description: 'Convert hexadecimal numbers to decimal',
    longDescription: 'Convert hexadecimal (base-16) numbers to decimal (base-10). Supports 0x prefix.',
    category: 'utility',
    inputLanguage: 'plaintext',
    outputLanguage: 'plaintext',
    inputPlaceholder: 'FF',
    convert: hexToDecimal,
    seoTitle: 'Hex to Decimal Converter – Free Online Tool',
    seoDescription: 'Convert hexadecimal to decimal online. Supports 0x prefix. Free number converter.',
    seoKeywords: ['hex to decimal', 'hexadecimal to decimal', 'hex converter'],
    relatedConverters: ['decimal-to-hex', 'binary-to-decimal'],
  },
  {
    id: 'timestamp-to-date',
    name: 'Timestamp to Date',
    shortName: 'Timestamp → Date',
    description: 'Convert Unix timestamp to human-readable date',
    longDescription: 'Convert Unix timestamps (seconds or milliseconds) to human-readable dates. Shows ISO 8601, UTC, and local time formats.',
    category: 'utility',
    inputLanguage: 'plaintext',
    outputLanguage: 'json',
    inputPlaceholder: '1716239022',
    convert: timestampToDate,
    options: [{ key: 'timezone', type: 'timezone', label: 'Timezone' }],
    seoTitle: 'Unix Timestamp to Date Converter – Free Online Tool',
    seoDescription: 'Convert Unix timestamp to date online. Supports seconds and milliseconds. Shows ISO 8601, UTC, and local time.',
    seoKeywords: ['timestamp to date', 'unix timestamp converter', 'epoch to date', 'timestamp converter'],
    relatedConverters: ['date-to-timestamp'],
    isPopular: true,
  },
  {
    id: 'date-to-timestamp',
    name: 'Date to Timestamp',
    shortName: 'Date → Timestamp',
    description: 'Convert date strings to Unix timestamps',
    longDescription: 'Convert human-readable date strings to Unix timestamps (seconds and milliseconds). Accepts ISO 8601 and many other date formats.',
    category: 'utility',
    inputLanguage: 'plaintext',
    outputLanguage: 'json',
    inputPlaceholder: '2024-01-15T10:30:00Z',
    convert: dateToTimestamp,
    options: [{ key: 'timezone', type: 'timezone', label: 'Timezone' }],
    seoTitle: 'Date to Unix Timestamp Converter – Free Online Tool',
    seoDescription: 'Convert date to Unix timestamp online. Free epoch timestamp converter.',
    seoKeywords: ['date to timestamp', 'date to epoch', 'datetime to unix', 'timestamp converter'],
    relatedConverters: ['timestamp-to-date'],
  },

  // ── Color Category ──────────────────────────────────────────────────────
  {
    id: 'hex-to-rgb',
    name: 'HEX to RGB/HSL',
    shortName: 'HEX → RGB',
    description: 'Convert HEX colors to RGB, HSL, and CSS variables',
    longDescription: 'Convert HEX color codes to RGB, RGBA, HSL, HSLA values and CSS custom properties. Supports both 3-digit and 6-digit hex codes.',
    category: 'color',
    inputLanguage: 'plaintext',
    outputLanguage: 'json',
    inputPlaceholder: '#1677FF',
    convert: hexToAll,
    seoTitle: 'HEX to RGB Color Converter – Free Online Tool',
    seoDescription: 'Convert HEX color to RGB, RGBA, HSL, and CSS variables online. Free color format converter.',
    seoKeywords: ['hex to rgb', 'hex to rgba', 'hex to hsl', 'color converter', 'hex color converter'],
    urlAliases: ['hex-to-rgba', 'hex-to-hsl', 'hex-color-converter'],
    relatedConverters: ['rgb-to-hex', 'hsl-to-rgb'],
    isPopular: true,
  },
  {
    id: 'rgb-to-hex',
    name: 'RGB to HEX/HSL',
    shortName: 'RGB → HEX',
    description: 'Convert RGB colors to HEX, HSL, and CSS variables',
    longDescription: 'Convert RGB or RGBA color values to HEX codes, HSL, and CSS custom properties. Accepts rgb() format or comma-separated values.',
    category: 'color',
    inputLanguage: 'plaintext',
    outputLanguage: 'json',
    inputPlaceholder: 'rgb(22, 119, 255)',
    convert: rgbToAll,
    seoTitle: 'RGB to HEX Color Converter – Free Online Tool',
    seoDescription: 'Convert RGB to HEX color code online. Also generates HSL and CSS variables. Free color converter.',
    seoKeywords: ['rgb to hex', 'rgb hex converter', 'color code converter', 'rgb to color code'],
    urlAliases: ['rgb-to-hsl'],
    relatedConverters: ['hex-to-rgb', 'hsl-to-rgb'],
  },
  {
    id: 'hsl-to-rgb',
    name: 'HSL to HEX/RGB',
    shortName: 'HSL → HEX',
    description: 'Convert HSL colors to HEX and RGB formats',
    longDescription: 'Convert HSL (Hue, Saturation, Lightness) color values to HEX, RGB, and CSS variables.',
    category: 'color',
    inputLanguage: 'plaintext',
    outputLanguage: 'json',
    inputPlaceholder: 'hsl(213, 100%, 54%)',
    convert: hslToAll,
    seoTitle: 'HSL to HEX/RGB Color Converter – Free Online Tool',
    seoDescription: 'Convert HSL to HEX and RGB online. Free color format converter.',
    seoKeywords: ['hsl to hex', 'hsl to rgb', 'hsl color converter'],
    relatedConverters: ['hex-to-rgb', 'rgb-to-hex'],
  },
  {
    id: 'css-minify',
    name: 'CSS Minify',
    shortName: 'CSS Minify',
    description: 'Minify CSS by removing whitespace and comments',
    longDescription: 'Compress CSS files by removing comments, whitespace, and redundant semicolons. Reduces file size for faster page loading.',
    category: 'code',
    inputLanguage: 'css',
    outputLanguage: 'css',
    inputPlaceholder: '/* Main styles */\n.container {\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  padding: 16px;\n}\n\n.button {\n  background-color: #1677ff;\n  color: white;\n  border: none;\n  border-radius: 4px;\n}',
    convert: cssMinify,
    seoTitle: 'CSS Minifier – Compress CSS Online | Free Tool',
    seoDescription: 'Minify and compress CSS online. Remove whitespace and comments to reduce CSS file size. Free CSS minifier.',
    seoKeywords: ['css minify', 'css minifier', 'compress css', 'css compressor', 'minimize css'],
    relatedConverters: ['css-beautify', 'css-to-scss'],
  },
  {
    id: 'css-beautify',
    name: 'CSS Beautify',
    shortName: 'CSS Beautify',
    description: 'Format and pretty-print CSS code',
    longDescription: 'Beautify and format minified or messy CSS with proper indentation and line breaks. Makes CSS human-readable and maintainable.',
    category: 'code',
    inputLanguage: 'css',
    outputLanguage: 'css',
    inputPlaceholder: '.container{display:flex;flex-direction:column;align-items:center}.button{background:#1677ff;color:white;border:none}',
    convert: cssBeautify,
    seoTitle: 'CSS Formatter & Beautifier – Free Online Tool',
    seoDescription: 'Beautify and format CSS online. Add proper indentation to minified CSS. Free CSS formatter.',
    seoKeywords: ['css formatter', 'css beautify', 'css pretty print', 'format css'],
    relatedConverters: ['css-minify', 'css-to-scss'],
  },
  {
    id: 'css-to-scss',
    name: 'CSS to SCSS',
    shortName: 'CSS → SCSS',
    description: 'Convert CSS custom properties to SCSS variables',
    longDescription: 'Convert CSS files to SCSS syntax. Transforms CSS custom properties (:root variables) to SCSS variables and var() references. Manual nesting required.',
    category: 'code',
    inputLanguage: 'css',
    outputLanguage: 'scss',
    inputPlaceholder: ':root {\n  --primary-color: #1677ff;\n  --font-size-base: 14px;\n  --border-radius: 6px;\n}\n\n.button {\n  background: var(--primary-color);\n  font-size: var(--font-size-base);\n  border-radius: var(--border-radius);\n}',
    convert: cssToScss,
    seoTitle: 'CSS to SCSS Converter – Free Online Tool',
    seoDescription: 'Convert CSS to SCSS online. Transform CSS variables to SCSS variables. Free developer tool.',
    seoKeywords: ['css to scss', 'css scss converter', 'convert css to scss', 'css to sass'],
    urlAliases: ['css-to-sass'],
    relatedConverters: ['css-beautify', 'css-minify'],
  },
  {
    id: 'css-to-tailwind',
    name: 'CSS to Tailwind',
    shortName: 'CSS → Tailwind',
    description: 'Convert CSS properties to Tailwind CSS utility classes',
    longDescription: 'Convert CSS declarations to Tailwind CSS utility class names. Supports layout, flexbox, spacing, and typography properties. Complex values may need manual conversion.',
    category: 'code',
    inputLanguage: 'css',
    outputLanguage: 'plaintext',
    inputPlaceholder: 'display: flex;\nflex-direction: column;\nalign-items: center;\njustify-content: space-between;\nposition: relative;\noverflow: hidden;',
    convert: cssToTailwind,
    seoTitle: 'CSS to Tailwind CSS Converter – Free Online Tool',
    seoDescription: 'Convert CSS to Tailwind utility classes online. Free CSS to Tailwind converter for developers.',
    seoKeywords: ['css to tailwind', 'tailwind converter', 'css tailwind', 'convert css to tailwind'],
    relatedConverters: ['css-beautify', 'css-minify'],
    isPopular: true,
  },
]

// ─── Lookup Helpers ────────────────────────────────────────────────────────

/** Map of id → Converter */
export const CONVERTER_MAP = new Map<string, Converter>(
  CONVERTERS.map((c) => [c.id, c])
)

/** Map of alias → canonical id */
export const ALIAS_MAP = new Map<string, string>(
  CONVERTERS.flatMap((c) =>
    (c.urlAliases ?? []).map((alias) => [alias, c.id])
  )
)

/** Resolve a URL slug to a Converter (checks aliases too) */
export function resolveConverter(slug: string): Converter | undefined {
  return CONVERTER_MAP.get(slug) ?? CONVERTER_MAP.get(ALIAS_MAP.get(slug) ?? '')
}

/** Get popular converters for home page hero */
export const POPULAR_CONVERTERS = CONVERTERS.filter((c) => c.isPopular)

/**
 * Find a converter by exact inputLanguage + outputLanguage pair.
 * Returns the first match (most specific) or undefined.
 */
export function findConverterByLangs(
  inputLang: string,
  outputLang: string
): Converter | undefined {
  return CONVERTERS.find(
    (c) => c.inputLanguage === inputLang && c.outputLanguage === outputLang
  )
}

/**
 * Get all unique output languages available for a given input language.
 * Used to populate the output dropdown with only valid options.
 */
export function getOutputLangsFor(inputLang: string): string[] {
  const seen = new Set<string>()
  return CONVERTERS
    .filter((c) => c.inputLanguage === inputLang)
    .map((c) => c.outputLanguage)
    .filter((lang) => (seen.has(lang) ? false : seen.add(lang) && true))
}

/**
 * Get all unique input languages that have at least one converter.
 */
export function getAllInputLangs(): string[] {
  const seen = new Set<string>()
  return CONVERTERS
    .map((c) => c.inputLanguage)
    .filter((lang) => (seen.has(lang) ? false : seen.add(lang) && true))
}

/** Group converters by category */
export function getConvertersByCategory(category: ConverterCategory): Converter[] {
  return CONVERTERS.filter((c) => c.category === category)
}

export const ALL_CATEGORIES: { key: ConverterCategory; label: string; emoji: string }[] = [
  { key: 'json', label: 'JSON / YAML / XML', emoji: '📄' },
  { key: 'code', label: 'Code & Styles', emoji: '⚡' },
  { key: 'markup', label: 'Markup', emoji: '🏷️' },
  { key: 'encoding', label: 'Encoding', emoji: '🔐' },
  { key: 'color', label: 'Colors', emoji: '🎨' },
  { key: 'data', label: 'Data', emoji: '📊' },
  { key: 'utility', label: 'Utility', emoji: '🔧' },
]

export default CONVERTERS
